export const UPDATE_NOTIFICATION_STATE =
  '@notification/UPDATE_NOTIFICATION_STATE';

export const START_REGISTER_DEVICE_TOKEN =
  '@notification/START_REGISTER_DEVICE_TOKEN';
export const REGISTER_DEVICE_TOKEN_SUCCESS =
  '@notification/REGISTER_DEVICE_TOKEN_SUCCESS';
export const REGISTER_DEVICE_TOKEN_FAILED =
  '@notification/REGISTER_DEVICE_TOKEN_FAILED';

export const START_UNREGISTER_DEVICE_TOKEN =
  '@notification/START_UNREGISTER_DEVICE_TOKEN';
export const UNREGISTER_DEVICE_TOKEN_SUCCESS =
  '@notification/UNREGISTER_DEVICE_TOKEN_SUCCESS';
export const UNREGISTER_DEVICE_TOKEN_FAILED =
  '@notification/UNREGISTER_DEVICE_TOKEN_FAILED';
