export const UPDATE_SETTINGS_STATE = '@settings/UPDATE_SETTINGS_STATE';

// Get filter details
export const GET_CUSTOMER_SETTINGS = '@settings/GET_CUSTOMER_SETTINGS';
export const GET_CUSTOMER_SETTINGS_SUCCESS =
  '@settings/GET_CUSTOMER_SETTINGS_SUCCESS';
export const GET_CUSTOMER_SETTINGS_FAILED =
  '@settings/GET_CUSTOMER_SETTINGS_FAILED';

// Update settings
export const UPDATE_CUSTOMER_SETTINGS = '@settings/UPDATE_CUSTOMER_SETTINGS';
export const UPDATE_CUSTOMER_SETTINGS_SUCCESS =
  '@settings/UPDATE_CUSTOMER_SETTINGS_SUCCESS';
export const UPDATE_CUSTOMER_SETTINGS_FAILED =
  '@settings/UPDATE_CUSTOMER_SETTINGS_FAILED';

// Get customer survey
export const GET_CUSTOMER_SURVEY = '@settings/GET_CUSTOMER_SURVEY';
export const GET_CUSTOMER_SURVEY_SUCCESS =
  '@settings/GET_CUSTOMER_SURVEY_SUCCESS';
export const GET_CUSTOMER_SURVEY_FAILED =
  '@settings/GET_CUSTOMER_SURVEY_FAILED';

// Update customer survey
export const UPDATE_CUSTOMER_SURVEY = '@settings/UPDATE_CUSTOMER_SURVEY';
export const UPDATE_CUSTOMER_SURVEY_SUCCESS =
  '@settings/UPDATE_CUSTOMER_SURVEY_SUCCESS';
export const UPDATE_CUSTOMER_SURVEY_FAILED =
  '@settings/UPDATE_CUSTOMER_SURVEY_FAILED';
