export enum TREStatus {
  APPLICATION_ERROR = 'APPLICATION_ERROR',
  BAD_PASSWORD = 'BAD_PASSWORD',
  CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS',
  EMAIL_CODE_REQUIRED = 'EMAIL_CODE_REQUIRED',
  GENERIC_SUCCESS = 'GENERIC_SUCCESS',
  INVALID_ACCESS = 'INVALID_ACCESS',
  INVALID_OTP_CODE = 'INVALID_OTP_CODE',
  INCORRECT_USER_OR_PASSWORD = 'INCORRECT_USER_OR_PASSWORD',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY',
  NEW_PASSWORD_REQUIRED = 'NEW_PASSWORD_REQUIRED',
  OTP_REQUIRED = 'OTP_REQUIRED',
  REFREH_TOKEN_SUCCESS = 'REFREH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL',
  SERVER_ERROR = 'SERVER_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  USERNAME_EXISTS = 'USERNAME_EXISTS',

  // THESE ARE FOR CUSTOMER
  UPSERT_COMPATIBILITY_ANSWER_SUCCESS = 'UPSERT_COMPATIBILITY_ANSWER_SUCCESS',
  UPSERT_CUSTOMER_DETAILS_SUCCESS = 'UPSERT_CUSTOMER_DETAILS_SUCCESS',
  GET_CUSTOMER_DETAILS_SUCCESS = 'GET_CUSTOMER_DETAILS_SUCCESS',
  GET_CUSTOMER_PHOTO_SUCCESS = 'GET_CUSTOMER_PHOTO_SUCCESS',
  GET_CUSTOMER_FIRST_PIC_SUCCESS = 'GET_CUSTOMER_FIRST_PIC_SUCCESS',
  GET_CUSTOMER_SETTINGS_SUCCESS = 'GET_CUSTOMER_SETTINGS_SUCCESS',
  UPLOAD_CUSTOMER_PHOTO_SUCCESS = 'UPLOAD_CUSTOMER_PHOTO_SUCCESS',
  UPDATE_CUSTOMER_FILTER_SUCCESS = 'UPDATE_CUSTOMER_FILTER_SUCCESS',
  UPDATE_CUSTOMER_SETTINGS_SUCCESS = 'UPDATE_CUSTOMER_SETTINGS_SUCCESS',
  UPSERT_CUSTOMER_SURVEY_SUCCESS = 'UPSERT_CUSTOMER_SURVEY_SUCCESS',
  GET_CUSTOMER_SURVEY_SUCCESS = 'GET_CUSTOMER_SURVEY_SUCCESS',
  DEACTIVATE_CUSTOMER_SUCCESS = 'DEACTIVATE_CUSTOMER_SUCCESS',
  ACTIVATE_CUSTOMER_SUCCESS = 'ACTIVATE_CUSTOMER_SUCCESS',
  DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS',
  DELETE_NON_EXISTING_COGNITO_USER_SUCCESS = 'DELETE_NON_EXISTING_COGNITO_USER_SUCCESS',

  INVALID_QUESTION = 'INVALID_QUESTION',
  INVALID_ANSWER = 'INVALID_ANSWER',
  CUSTOMER_ERROR = 'CUSTOMER_ERROR',
  INVALID_COMPATIBILITIES_EXCEPTION = 'INVALID_COMPATIBILITIES_EXCEPTION',

  // USUALLY SHOULD NOT HAPPEN, BUT HEY, THINGS HAPPEN.
  MAX_PROFILE_PHOTO_EXCEEDED = 'MAX_PROFILE_PHOTO_EXCEEDED',

  // MAXIMUM SWIPES
  MATCH_EXCEPTION = 'MATCH_EXCEPTION',

  MAX_SWIPES = 'MAX_SWIPES',
  POSSIBLES_COOLDOWN_EXCEPTION = 'POSSIBLES_COOLDOWN_EXCEPTION',
  USER_NOT_SUBSCRIBED = 'USER_NOT_SUBSCRIBED',

  S3_UPLOAD_FAIL = 'S3_UPLOAD_FAIL',

  // Facial verification statuses
  SMILE_CHECK_FAILED = 'SMILE_CHECK_FAILED',
  SMILE_CHECK_NO_FACES_FOUND = 'SMILE_CHECK_NO_FACES_FOUND',
  SMILE_CHECK_HAS_MULTIPLE_FACES = 'SMILE_CHECK_HAS_MULTIPLE_FACES',
  PROFILE_DOES_NOT_HAVE_THREE_PHOTOS = 'PROFILE_DOES_NOT_HAVE_THREE_PHOTOS',
  PROFILE_PHOTOS_DOES_NOT_MATCH = 'PROFILE_PHOTOS_DOES_NOT_MATCH',
  VERIFICATION_IN_PROGRESS_ERROR = 'VERIFICATION_IN_PROGRESS_ERROR',
  NONE_OR_INVALID_FILES = 'NONE_OR_INVALID_FILES',
  NEW_PRIMARY_PHOTO_DOES_NOT_MATCH = 'NEW_PRIMARY_PHOTO_DOES_NOT_MATCH',
}
