import {StyleSheet} from 'react-native';
import {COLORS, SIZES, width} from '../../../constants/commons.ts';
import {moderateScale, scale} from '../../../utils/utils.ts';

export const profileCreationStyles = StyleSheet.create({
  flex: {flex: 1},
  container: {backgroundColor: COLORS.white, flex: 1},
  backButtonContainer: {flex: 0.1, marginTop: 32, marginLeft: 14},
  backButton: {width: scale(30), alignItems: 'flex-start'},
  backImage: {alignSelf: 'flex-start'},
  titleContainer: {flex: 0.9, marginHorizontal: 30, marginTop: 30},
  textTitle: {
    fontSize: SIZES.h2,
    fontFamily: 'ClimateCrisis-Regular',
    color: COLORS.primary1,
  },
  textSubtitle: {
    fontSize: SIZES.h5,
    fontFamily: 'Montserrat-SemiBold',
    color: COLORS.gray,
    letterSpacing: -0.6,
  },
  textInputContainer: {
    marginTop: 100,
    marginBottom: 50,
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  textInputStyle: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: 1,
  },
  textInput: {
    backgroundColor: COLORS.white,
    fontSize: SIZES.h3,
    fontFamily: 'Montserrat-Medium',
    padding: 0,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.black,
  },
  bodyContainer: {},
  textBody: {
    fontSize: SIZES.h5,
    fontFamily: 'Montserrat-SemiBold',
    color: COLORS.gray,
    letterSpacing: -0.6,
  },
  buttonContainer: {marginHorizontal: 30, alignItems: 'center'},
  buttonStyle: {
    alignItems: 'center',
    maxWidth: width,
    width: width - 64,
    height: 50,
    justifyContent: 'center',
    borderRadius: 30,
    marginBottom: 12,
  },
  buttonTextStyle: {
    letterSpacing: -0.4,
    fontFamily: 'Montserrat-SemiBold',
    color: COLORS.white,
    fontSize: SIZES.h5,
  },
  errorText: {
    marginTop: 8,
    color: COLORS.primary1,
    fontFamily: 'Montserrat-Regular',
    letterSpacing: -0.8,
    fontSize: SIZES.h6,
  },
  dropdownContainer: {
    marginTop: 100,
    marginBottom: 50,
    flexDirection: 'row',
    // justifyContent: 'space-around',
    gap: 6,
  },
  dropdownSection: {
    flex: 1,
  },
  gridContainer: {
    marginTop: 100,
    marginBottom: 50,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  textImage: {
    fontSize: SIZES.h2,
    fontFamily: 'ClimateCrisis-Regular',
    color: COLORS.primary1,
  },
  imageContainer: {
    marginTop: 45,
    marginBottom: 50,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  cardContainer: {
    marginTop: 75,
    marginBottom: 50,
    flex: 1,
    flexDirection: 'column',
    padding: 30,
    backgroundColor: 'white',
    borderRadius: 15,
  },
  buttonInterestContainer: {
    marginTop: 35,
    flex: 1,

    // flexDirection: 'column'
  },
  footerContainer: {
    marginHorizontal: 30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  skipText: {
    fontFamily: 'Montserrat-ExtraBold',
    fontSize: moderateScale(13),
    letterSpacing: -0.4,
    color: COLORS.black,
  },
  bodyDropdownContainer: {
    marginTop: 35,
    marginBottom: 50,
    flexDirection: 'column',
    gap: 22,
  },
  dropdownContainer2: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    // borderWidth: 1,
    gap: 6,
  },
  dropdownSection2: {
    flex: 1,
  },
  dropdownTitle: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 16,
    letterSpacing: -0.4,
    color: COLORS.black,
  },
  bodyPhotoContainer: {
    marginTop: 35,
    // marginBottom: 50,
    flexDirection: 'column',
  },
  onboardingTitleContainer: {
    marginHorizontal: 30,
    marginTop: 10,
    flexDirection: 'column',
  },
  onboardingImage: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  // onboardingTextSubtitle: {
  //   fontSize: SIZES.h4,
  //
  //   fontFamily: 'ClimateCrisis-Regular',
  //   color: COLORS.primary1,
  // },
  // onboardingTextTitle: {
  //   fontSize: SIZES.h1,
  //   fontFamily: 'ClimateCrisis-Regular',
  //   color: COLORS.primary1,
  //
  //   marginVertical: -12,
  // },
  questionTitle: {
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
    fontSize: moderateScale(20),
    marginBottom: 14,
  },
  questionButton: {
    height: 50,
    borderWidth: 1,
    borderColor: COLORS.gray,
    marginBottom: 8,
    borderRadius: 30,
    justifyContent: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  letterChoice: {
    paddingHorizontal: 20,
    fontFamily: 'ClimateCrisis-Regular',
    fontSize: scale(30),
    color: COLORS.secondary1,
    marginTop: scale(-8),
  },
  answerText: {
    color: COLORS.gray3,
    fontSize: 15,
    letterSpacing: -0.4,
    fontFamily: 'Montserrat-Medium',
    flex: 1,
  },
  textInputBio: {
    backgroundColor: COLORS.white,
    fontSize: SIZES.h4,
    fontFamily: 'Montserrat-Medium',
    // padding: 0,
    width: '100%',
    borderWidth: 1,
    borderColor: COLORS.black,
    borderRadius: 25,
    paddingHorizontal: 16,
    minHeight: 120,
    maxHeight: 120,
    paddingTop: 8,
  },
  textInputBioWork: {
    backgroundColor: COLORS.white,
    fontSize: SIZES.h4,
    fontFamily: 'Montserrat-Medium',
    borderRadius: 25,
    padding: 16,
    width: '100%',
    borderWidth: 1,
    borderColor: COLORS.black,
  },
});
