import {Chat} from '../../../types/generated.ts';

export const chatMockList: Chat[] = [
  {
    profile: {
      sub: 'cd9001a6-5f4f-47f9-bf6b-887ff8d727db',
      name: 'Michelina Makeswell',
      gender: 'Lesbian',
      birthday: '1988-10-03',
      hometown: 'Salamanca',
      deactivateDate: null,
      customerDetails: {
        bio: 'Here lang for fun',
        work: 'Fashion',
        location: 'Salamanca',
        height: '5ft 7in',
        starSign: 'Taurus',
        education: 'Doctorate',
        drinking: 'Regular',
        smoking: 'Never',
        religion: 'Christian',
        pet: 'Bird',
        politics: 'Apolitical',
        personalityType: 'Beaver',
        hobbies: '',
      },
      withCustomerDetails: true,
      withCustomerCompatibilities: true,
      customerPhoto: [
        {
          id: 1888,
          primary: true,
          photoUrl:
            'https://images.unsplash.com/photo-1557053910-d9eadeed1c58?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
          index: null,
        },
        // ... more photos
      ],
      withCustomerPhoto: true,
      activated: true,
    },
    lastMessage: 'Hey, how are you?',
    lastActivity: 1677605278000,
    chatRoomUuid: 'a8sdd8u-a89su8-98sad-as89du',
    tag: 'JOWA',
  },
  {
    profile: {
      sub: '0ce0843b-0e7d-42f4-9ee4-36c52fec4b25',
      name: 'Lindie Stearn',
      gender: 'Gender Variant',
      birthday: '1967-02-11',
      hometown: 'Biga',
      deactivateDate: null,
      customerDetails: {
        bio: 'diam cras pellentesque volutpat...',
        work: 'Web Developer IV',
        location: 'Biga',
        height: '6ft 1in',
        starSign: 'Leo',
        education: 'Highschool',
        drinking: 'Occasional',
        smoking: 'Occasional',
        religion: 'Catholic',
        pet: 'Dog',
        politics: 'Conservative',
        personalityType: 'Beaver',
        hobbies: '',
      },
      withCustomerDetails: true,
      withCustomerCompatibilities: true,
      customerPhoto: [
        {
          id: 1296,
          primary: true,
          photoUrl:
            'https://images.unsplash.com/photo-1584043720379-b56cd9199c94?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
          index: null,
        },
      ],
      withCustomerPhoto: true,
      activated: true,
    },
    lastMessage: 'Sounds interesting! What else do you like to do?',
    lastActivity: 1677613445000,
    chatRoomUuid: '9832hjs-8832hs-38s8u3-0s9a8',
    tag: 'MARE',
  },
  {
    profile: {
      sub: '5f39b22d-c9b7-4577-b8a7-870eb43ce4b7',
      name: 'Ree Cattrall',
      gender: 'Gender Fluid',
      birthday: '1962-09-24',
      hometown: 'Luklukan',
      deactivateDate: null,
      customerDetails: {
        bio: 'in lacus curabitur at ipsum...',
        work: 'Sales Representative',
        location: 'Luklukan',
        height: '4ft 6in',
        starSign: 'Pisces',
        education: 'Doctorate',
        drinking: 'Never',
        smoking: 'Regular',
        religion: 'Christian',
        pet: 'Dog',
        politics: 'Conservative',
        personalityType: 'Lion',
        hobbies: '',
      },
      withCustomerDetails: true,
      withCustomerCompatibilities: true,
      customerPhoto: [
        {
          id: 1679,
          primary: true,
          photoUrl:
            'https://images.unsplash.com/photo-1570824629069-2de4bcd4345a?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
          index: null,
        },
      ],
      withCustomerPhoto: true,
      activated: true,
    },
    lastMessage: 'Lol, I like how direct you are!',
    lastActivity: 1677595278000,
    chatRoomUuid: '12j3klj-4u5j34-j4534h-2j34kl',
    tag: 'JOWA', // No tag for this one
  },
  {
    profile: {
      sub: '364ffbd2-4e3d-4e7a-b07d-8124b40e741c',
      name: 'Carita Powis',
      gender: 'Female to Male',
      birthday: '1962-02-22',
      hometown: 'San Juan',
      deactivateDate: null,
      customerDetails: {
        bio: 'morbi non quam nec dui luctus...',
        work: 'Health Coach III',
        location: 'San Juan',
        height: '7ft 8in',
        starSign: 'Cancer',
        education: 'Doctorate',
        drinking: 'Never',
        smoking: 'Regular',
        religion: 'Muslim',
        pet: 'Dog',
        politics: 'Liberal',
        personalityType: 'Dog',
        hobbies: '',
      },
      withCustomerDetails: true,
      withCustomerCompatibilities: true,
      customerPhoto: [
        {
          id: 2069,
          primary: true,
          photoUrl:
            'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
          index: null,
        },
      ],
      withCustomerPhoto: true,
      activated: true,
    },
    lastMessage: 'What kind of music are you into?',
    lastActivity: 1677609930000,
    chatRoomUuid: 'a09d8su-90a8su8-98sad-as234u',
    tag: 'JOWA',
  },
  {
    profile: {
      sub: 'd32680d6-3fe0-4ca4-8b63-44a9d0e6d331',
      name: 'Kevina Sare',
      gender: 'Gender Fluid',
      birthday: '1969-03-01',
      hometown: 'Loay',
      deactivateDate: null,
      customerDetails: {
        bio: 'dis parturient montes nascetur...',
        work: 'Research Associate',
        location: 'Loay',
        height: '4ft 5in',
        starSign: 'Aquarius',
        education: 'Bachelor',
        drinking: 'Occasional',
        smoking: 'Never',
        religion: 'Buddhist',
        pet: 'Fish',
        politics: 'Moderate',
        personalityType: 'Otter',
        hobbies: '',
      },
      withCustomerDetails: true,
      withCustomerCompatibilities: true,
      customerPhoto: [
        {
          id: 1493,
          primary: true,
          photoUrl:
            'https://images.unsplash.com/photo-1607529378676-a20456ee2f6b?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
          index: null,
        },
      ],
      withCustomerPhoto: true,
      activated: true,
    },
    lastMessage: 'Sure, when are you free?',
    lastActivity: 1677614888000,
    chatRoomUuid: '837hsd-2h38hs-h83hsd-8as7jd',
    tag: 'MARE',
  },
];
