export const UPDATE_PROFILE_CREATION_STATE =
  '@profileCreation/UPDATE_PROFILE_CREATION_STATE';

// Initial Profile Creation
export const START_PROFILE_CREATION = '@profileCreation/START_PROFILE_CREATION';
export const START_PROFILE_CREATION_SUCCESS =
  '@profileCreation/START_PROFILE_CREATION_SUCCESS';
export const START_PROFILE_CREATION_FAILED =
  '@profileCreation/START_PROFILE_CREATION_FAILED';

// Get Compatibility Questions
export const GET_COMPATIBILTY_QUESTIONS =
  '@profileCreation/GET_COMPATIBILTY_QUESTIONS';
export const GET_COMPATIBILTY_QUESTIONS_SUCCESS =
  '@profileCreation/GET_COMPATIBILTY_QUESTIONS_SUCCESS';
export const GET_COMPATIBILTY_QUESTIONS_FAILED =
  '@profileCreation/GET_COMPATIBILTY_QUESTIONS_FAILED';

// Submit Compatibility Answer
export const SUBMIT_COMPATIBILITY_ANSWER =
  '@profileCreation/SUBMIT_COMPATIBILITY_ANSWER';
export const SUBMIT_COMPATIBILITY_ANSWER_SUCCESS =
  '@profileCreation/SUBMIT_COMPATIBILITY_ANSWER_SUCCESS';
export const SUBMIT_COMPATIBILITY_ANSWER_FAILED =
  '@profileCreation/SUBMIT_COMPATIBILITY_ANSWER_FAILED';

// Submit Customer Details
export const SUBMIT_CUSTOMER_DETAILS =
  '@profileCreation/SUBMIT_CUSTOMER_DETAILS';
export const SUBMIT_CUSTOMER_DETAILS_SUCCESS =
  '@profileCreation/SUBMIT_CUSTOMER_DETAILS_SUCCESS';
export const SUBMIT_CUSTOMER_DETAILS_FAILED =
  '@profileCreation/SUBMIT_CUSTOMER_DETAILS_FAILED';

// UPLOAD PHOTO
export const UPLOAD_PHOTO = '@profileCreation/UPLOAD_PHOTO';
export const UPLOAD_PHOTO_SUCCESS = '@profileCreation/UPLOAD_PHOTO_SUCCESS';
export const UPLOAD_PHOTO_FAILED = '@profileCreation/UPLOAD_PHOTO_FAILED';
