export const UPDATE_SSO_VALIDATION_STATE =
  '@ssoValidation/UPDATE_SSO_VALIDATION_STATE';

// Mobile validation
export const START_SSO_MOBILE_VALIDATION =
  '@ssoValidation/START_SSO_MOBILE_VALIDATION';
export const START_SSO_MOBILE_VALIDATION_SUCCESS =
  '@ssoValidation/START_SSO_MOBILE_VALIDATION_SUCCESS';
export const START_SSO_MOBILE_VALIDATION_FAILED =
  '@ssoValidation/START_SSO_MOBILE_VALIDATION_FAILED';

// Mobile verification
export const START_SSO_MOBILE_VERIFICATION =
  '@ssoValidation/START_SSO_MOBILE_VERIFICATION';
export const START_SSO_MOBILE_VERIFICATION_SUCCESS =
  '@ssoValidation/START_SSO_MOBILE_VERIFICATION_SUCCESS';
export const START_SSO_MOBILE_VERIFICATION_FAILED =
  '@ssoValidation/START_SSO_MOBILE_VERIFICATION_FAILED';

// Mobile Resend verification
export const START_SSO_MOBILE_RESEND_OTP =
  '@ssoValidation/START_SSO_MOBILE_RESEND_OTP';
export const START_SSO_MOBILE_RESEND_OTP_SUCCESS =
  '@ssoValidation/START_SSO_MOBILE_RESEND_OTP_SUCCESS';
export const START_SSO_MOBILE_RESEND_OTP_FAILED =
  '@ssoValidation/START_SSO_MOBILE_RESEND_OTP_FAILED';
