export const UPDATE_LOGIN_STATE = '@login/UPDATE_LOGIN_STATE';

export const START_LOGIN = '@login/START_LOGIN';
export const LOGIN_SUCCESS = '@login/LOGIN_SUCCESS';
export const LOGIN_FAILED = '@login/LOGIN_FAILED';

export const START_LOGOUT = '@login/START_LOGOUT';
export const START_LOGOUT_SUCCESS = '@login/START_LOGOUT_SUCCESS';
export const START_LOGOUT_FAILED = '@login/START_LOGOUT_FAILED';

export const START_LOGIN_VIA_REFRESH_TOKEN =
  '@login/START_LOGIN_VIA_REFRESH_TOKEN';
export const START_LOGIN_VIA_REFRESH_TOKEN_SUCCESS =
  '@login/START_LOGIN_VIA_REFRESH_TOKEN_SUCCESS';
export const START_LOGIN_VIA_REFRESH_TOKEN_FAILED =
  '@login/START_LOGIN_VIA_REFRESH_TOKEN_FAILED';
