export const UPDATE_MOBILE_EMAIL_STATE =
  '@mobileEmail/UPDATE_MOBILE_EMAIL_STATE';

// MOBILE INPUT
export const START_MOBILE_VALIDATION = '@mobileEmail/START_MOBILE_VALIDATION';
export const START_MOBILE_VALIDATION_SUCCESS =
  '@mobileEmail/START_MOBILE_VALIDATION_SUCCESS';
export const START_MOBILE_VALIDATION_FAILED =
  '@mobileEmail/START_MOBILE_VALIDATION_FAILED';

// MOBILE OTP
export const START_MOBILE_VERIFICATION =
  '@mobileEmail/START_MOBILE_VERIFICATION';
export const START_MOBILE_VERIFICATION_SUCCESS =
  '@mobileEmail/START_MOBILE_VERIFICATION_SUCCESS';
export const START_MOBILE_VERIFICATION_FAILED =
  '@mobileEmail/START_MOBILE_VERIFICATION_FAILED';

// EMAIL INPUT
export const START_EMAIL_VALIDATION = '@mobileEmail/START_EMAIL_VALIDATION';
export const START_EMAIL_VALIDATION_SUCCESS =
  '@mobileEmail/START_EMAIL_VALIDATION_SUCCESS';
export const START_EMAIL_VALIDATION_FAILED =
  '@mobileEmail/START_EMAIL_VALIDATION_FAILED';

// EMAIL OTP
export const START_EMAIL_VERIFICATION = '@mobileEmail/START_EMAIL_VERIFICATION';
export const START_EMAIL_VERIFICATION_SUCCESS =
  '@mobileEmail/START_EMAIL_VERIFICATION_SUCCESS';
export const START_EMAIL_VERIFICATION_FAILED =
  '@mobileEmail/START_EMAIL_VERIFICATION_FAILED';

// PASSWORD VALIDATION
export const START_PASSWORD_VALIDATION =
  '@mobileEmail/START_PASSWORD_VALIDATION';
export const START_PASSWORD_VALIDATION_SUCCESS =
  '@mobileEmail/START_PASSWORD_VALIDATION_SUCCESS';
export const START_PASSWORD_VALIDATION_FAILED =
  '@mobileEmail/START_PASSWORD_VALIDATION_FAILED';

// RESEND SMS OTP
export const START_RESEND_SMS_OTP = '@mobileEmail/START_RESEND_SMS_OTP';
export const START_RESEND_SMS_OTP_SUCCESS =
  '@mobileEmail/START_RESEND_SMS_OTP_SUCCESS';
export const START_RESEND_SMS_OTP_FAILED =
  '@mobileEmail/START_RESEND_SMS_OTP_FAILED';

// RESEND EMAIL OTP
export const START_RESEND_EMAIL_OTP = '@mobileEmail/START_RESEND_EMAIL_OTP';
export const START_RESEND_EMAIL_OTP_SUCCESS =
  '@mobileEmail/START_RESEND_EMAIL_OTP_SUCCESS';
export const START_RESEND_EMAIL_OTP_FAILED =
  '@mobileEmail/START_RESEND_EMAIL_OTP_FAILED';
