---
   name: Build the App on Test Environment
   run-name: ${{ github.actor }} is Triggering Develop Build 🚀
   on:
     push:
       branches:
         - test-build
   env:
     BUILD_NAME: 1.0.0
     BUILD_NUMBER: ${{github.run_number}}
     APP_NAME: ThundrDev
     APP_ID: ph.thundr.app.dev
   jobs:
     Git-Fetch-State:
       runs-on: aws
       steps:
         - name: Check out repository code
           uses: actions/checkout@v3
           with:
            fetch-depth: 0
         - run: echo "${{ github.event.head_commit.message }}"
     Package-Rename:
       runs-on: aws
       needs: Git-Fetch-State
       steps:
         - run: ls
         #- run: react-native-rename "${{ENV.APP_NAME}}" -b "${{ENV.APP_ID}}"
         - run: echo -en "sdk.dir = /usr/lib/android-sdk" >> android/local.properties
         - run: ls android
         - run: echo -en "${{VARS.DEV_ENV}}" >> .env
     Yarn-Install:
       runs-on: aws
       needs: Package-Rename
       steps:
         - run: yarn install
         - run: ls
     Android-Prepare-Build:
       runs-on: aws
       needs: Yarn-Install
       defaults:
         run:
           working-directory: ./android
       steps:
         - run: ls         
         - run: ./gradlew clean
     Android-APK-Build:
       runs-on: aws
       needs: Android-Prepare-Build
       defaults:
         run:
           working-directory: ./android
       steps:
         - run: ls
         - run: ./gradlew assembleRelease
     Android-APK-Upload:
       runs-on: aws
       needs: Android-APK-Build
       defaults:
         run:
           working-directory: ./android/app/build/outputs/apk/release
       steps:
         - run: ls
         - run: cp app-release.apk "thundr-dev-${{ github.run_number }}.apk"
         #- run: cp "thundr-dev-${{ github.run_number }}.apk" /Users/thundr/Documents/Projects/Thundr/artifacts/
     Android-AAB-Build:
       runs-on: aws
       needs: Android-Prepare-Build
       defaults:
         run:
           working-directory: ./android
       steps:
         - run: ls
         - run: ./gradlew bundleRelease
     Android-AAB-Upload:
       runs-on: aws
       needs: Android-AAB-Build
       defaults:
         run:
           working-directory: ./android/app/build/outputs/bundle/release
       steps:
         - run: ls
         - run: cp app-release.aab "thundr-dev-${{ github.run_number }}.aab"
         #- run: cp "thundr-dev-${{ github.run_number }}.aab" /Users/thundr/Documents/Projects/Thundr/artifacts/    
   concurrency:
     group: thundr-mobile-test
     cancel-in-progress: false
  