name: Checking for commits
run-name: ${{ github.actor }} is Triggering Push Commit Checks 🚀
on: 
  push:    
    branches-ignore :
      - develop-build
jobs:
  Git-Fetch-State:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: ls
  Yarn-Install:
        runs-on: self-hosted
        needs: Git-Fetch-State
        steps:
            - run: yarn install
  Lint-Test:
    runs-on: self-hosted
    needs: Yarn-Install
    continue-on-error: true
    steps:
      - run: ls
      - run: yarn lint
  Unit-Test:
    runs-on: self-hosted
    needs: Lint-Test
    continue-on-error: true
    steps:
      - run: ls
      - run: yarn test
  Sonar-Test:
    runs-on: self-hosted
    needs: Unit-Test
    steps:
      - run: ls
      - run: sonar-scanner -Dsonar.projectKey=thundr-mobile -Dsonar.sources=src -Dsonar.host.url=https://sonarqube.thundr.ph -Dsonar.token=${{secrets.SONAR_TOKEN}}
concurrency:
  group: thundr-mobile
  cancel-in-progress: false