export const UPDATE_DASHBOARD_STATE = '@dashboard/UPDATE_DASHBOARD_STATE';

// CUSTOMER DETAILS
export const GET_CUSTOMER_DETAILS = '@dashboard/GET_CUSTOMER_DETAILS';
export const GET_CUSTOMER_DETAILS_SUCCESS =
  '@dashboard/GET_CUSTOMER_DETAILS_SUCCESS';
export const GET_CUSTOMER_DETAILS_FAILED =
  '@dashboard/GET_CUSTOMER_DETAILS_FAILED';

// CUSTOMER PHOTO
export const GET_CUSTOMER_PHOTO = '@dashboard/GET_CUSTOMER_PHOTO';
export const GET_CUSTOMER_PHOTO_SUCCESS =
  '@dashboard/GET_CUSTOMER_PHOTO_SUCCESS';
export const GET_CUSTOMER_PHOTO_FAILED = '@dashboard/GET_CUSTOMER_PHOTO_FAILED';

// CUSTOMER PROFILE INCLUDES PHOTO AND DETAILS
export const GET_CUSTOMER_PROFILE = '@dashboard/GET_CUSTOMER_PROFILE';
export const GET_CUSTOMER_PROFILE_SUCCESS =
  '@dashboard/GET_CUSTOMER_PROFILE_SUCCESS';
export const GET_CUSTOMER_PROFILE_FAILED =
  '@dashboard/GET_CUSTOMER_PROFILE_FAILED';

// GET MATCH LIST DATA FOR SWIPING
export const GET_MATCH_LIST = '@dashboard/GET_MATCH_LIST';
export const GET_MATCH_LIST_SUCCESS = '@dashboard/GET_MATCH_LIST_SUCCESS';
export const GET_MATCH_LIST_FAILED = '@dashboard/GET_MATCH_LIST_FAILED';

// UPDATE CUSTOMER MATCH UPON SWIPE
export const CUSTOMER_MATCH = '@dashboard/CUSTOMER_MATCH';
export const CUSTOMER_MATCH_SUCCESS = '@dashboard/CUSTOMER_MATCH_SUCCESS';
export const CUSTOMER_MATCH_FAILED = '@dashboard/CUSTOMER_MATCH_FAILED';

// GET USER CURRENT LOCATION
export const UPDATE_CURRENT_LOCATION = '@dashboard/UPDATE_CURRENT_LOCATION';
export const UPDATE_CURRENT_LOCATION_SUCCESS =
  '@dashboard/UPDATE_CURRENT_LOCATION_SUCCESS';
export const UPDATE_CURRENT_LOCATION_FAILED =
  '@dashboard/UPDATE_CURRENT_LOCATION_FAILED';

// GET MATCH LIST FOR CHAT LIST
export const GET_CHAT_MATCH_LIST = '@dashboard/GET_CHAT_MATCH_LIST';
export const GET_CHAT_MATCH_LIST_SUCCESS =
  '@dashboard/GET_CHAT_MATCH_LIST_SUCCESS';
export const GET_CHAT_MATCH_LIST_FAILED =
  '@dashboard/GET_CHAT_MATCH_LIST_FAILED';

// GET CUSTOMER CHAT DETAILS
export const GET_CHAT_CUSTOMER_DETAILS = '@dashboard/GET_CHAT_CUSTOMER_DETAILS';
export const GET_CHAT_CUSTOMER_DETAILS_SUCCESS =
  '@dashboard/GET_CHAT_CUSTOMER_DETAILS_SUCCESS';
export const GET_CHAT_CUSTOMER_DETAILS_FAILED =
  '@dashboard/GET_CHAT_CUSTOMER_DETAILS_FAILED';

// SEND CHAT MESSAGES
export const SEND_MESSAGE = '@dashboard/SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = '@dashboard/SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = '@dashboard/SEND_MESSAGE_FAILED';
