export const UPDATE_DASHBOARD_STATE = '@dashboard/UPDATE_DASHBOARD_STATE';

export const GET_CUSTOMER_DETAILS = '@dashboard/GET_CUSTOMER_DETAILS';
export const GET_CUSTOMER_DETAILS_SUCCESS =
  '@dashboard/GET_CUSTOMER_DETAILS_SUCCESS';
export const GET_CUSTOMER_DETAILS_FAILED =
  '@dashboard/GET_CUSTOMER_DETAILS_FAILED';

export const GET_CUSTOMER_PHOTO = '@dashboard/GET_CUSTOMER_PHOTO';
export const GET_CUSTOMER_PHOTO_SUCCESS =
  '@dashboard/GET_CUSTOMER_PHOTO_SUCCESS';
export const GET_CUSTOMER_PHOTO_FAILED = '@dashboard/GET_CUSTOMER_PHOTO_FAILED';

export const GET_CUSTOMER_PROFILE = '@dashboard/GET_CUSTOMER_PROFILE';
export const GET_CUSTOMER_PROFILE_SUCCESS =
  '@dashboard/GET_CUSTOMER_PROFILE_SUCCESS';
export const GET_CUSTOMER_PROFILE_FAILED =
  '@dashboard/GET_CUSTOMER_PROFILE_FAILED';
