export const UPDATE_DASHBOARD_STATE = '@dashboard/UPDATE_DASHBOARD_STATE';

// CUSTOMER DETAILS
export const GET_CUSTOMER_DETAILS = '@dashboard/GET_CUSTOMER_DETAILS';
export const GET_CUSTOMER_DETAILS_SUCCESS =
  '@dashboard/GET_CUSTOMER_DETAILS_SUCCESS';
export const GET_CUSTOMER_DETAILS_FAILED =
  '@dashboard/GET_CUSTOMER_DETAILS_FAILED';

// CUSTOMER PHOTO
export const GET_CUSTOMER_PHOTO = '@dashboard/GET_CUSTOMER_PHOTO';
export const GET_CUSTOMER_PHOTO_SUCCESS =
  '@dashboard/GET_CUSTOMER_PHOTO_SUCCESS';
export const GET_CUSTOMER_PHOTO_FAILED = '@dashboard/GET_CUSTOMER_PHOTO_FAILED';

// CUSTOMER PROFILE INCLUDES PHOTO AND DETAILS
export const GET_CUSTOMER_PROFILE = '@dashboard/GET_CUSTOMER_PROFILE';
export const GET_CUSTOMER_PROFILE_SUCCESS =
  '@dashboard/GET_CUSTOMER_PROFILE_SUCCESS';
export const GET_CUSTOMER_PROFILE_FAILED =
  '@dashboard/GET_CUSTOMER_PROFILE_FAILED';

// GET CURRENT USER PROFILE
export const GET_CURRENT_USER_PROFILE = '@dashboard/GET_CURRENT_USER_PROFILE';
export const GET_CURRENT_USER_PROFILE_SUCCESS =
  '@dashboard/GET_CURRENT_USER_PROFILE_SUCCESS';
export const GET_CURRENT_USER_PROFILE_FAILED =
  '@dashboard/GET_CUSTOMER_PROFILE_FAILED';

// GET MATCH LIST DATA FOR SWIPING
export const GET_MATCH_LIST = '@dashboard/GET_MATCH_LIST';
export const GET_MATCH_LIST_SUCCESS = '@dashboard/GET_MATCH_LIST_SUCCESS';
export const GET_MATCH_LIST_FAILED = '@dashboard/GET_MATCH_LIST_FAILED';

// UPDATE CUSTOMER MATCH UPON SWIPE
export const CUSTOMER_MATCH = '@dashboard/CUSTOMER_MATCH';
export const CUSTOMER_MATCH_SUCCESS = '@dashboard/CUSTOMER_MATCH_SUCCESS';
export const CUSTOMER_MATCH_FAILED = '@dashboard/CUSTOMER_MATCH_FAILED';

// GET USER CURRENT LOCATION
export const UPDATE_CURRENT_LOCATION = '@dashboard/UPDATE_CURRENT_LOCATION';
export const UPDATE_CURRENT_LOCATION_SUCCESS =
  '@dashboard/UPDATE_CURRENT_LOCATION_SUCCESS';
export const UPDATE_CURRENT_LOCATION_FAILED =
  '@dashboard/UPDATE_CURRENT_LOCATION_FAILED';

// GET MATCH LIST FOR CHAT LIST
export const GET_CHAT_MATCH_LIST = '@dashboard/GET_CHAT_MATCH_LIST';
export const GET_CHAT_MATCH_LIST_SUCCESS =
  '@dashboard/GET_CHAT_MATCH_LIST_SUCCESS';
export const GET_CHAT_MATCH_LIST_FAILED =
  '@dashboard/GET_CHAT_MATCH_LIST_FAILED';

// GET CUSTOMER CHAT DETAILS FOR JOWA
export const GET_CHAT_CUSTOMER_DETAILS = '@dashboard/GET_CHAT_CUSTOMER_DETAILS';
export const GET_CHAT_CUSTOMER_DETAILS_SUCCESS =
  '@dashboard/GET_CHAT_CUSTOMER_DETAILS_SUCCESS';
export const GET_CHAT_CUSTOMER_DETAILS_FAILED =
  '@dashboard/GET_CHAT_CUSTOMER_DETAILS_FAILED';

// GET CUSTOMER CHAT DETAILS FOR MARE
export const GET_CHAT_CUSTOMER_DETAILS_MARE =
  '@dashboard/GET_CHAT_CUSTOMER_DETAILS_MARE';
export const GET_CHAT_CUSTOMER_DETAILS_MARE_SUCCESS =
  '@dashboard/GET_CHAT_CUSTOMER_DETAILS_MARE_SUCCESS';
export const GET_CHAT_CUSTOMER_DETAILS_MARE_FAILED =
  '@dashboard/GET_CHAT_CUSTOMER_DETAILS_MARE_FAILED';

// GET CHAT MESSAGES
export const GET_MESSAGE = '@dashboard/GET_MESSAGE';
export const GET_MESSAGE_SUCCESS = '@dashboard/GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_FAILED = '@dashboard/GET_MESSAGE_FAILED';

// SEND CHAT MESSAGES
export const SEND_MESSAGE = '@dashboard/SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = '@dashboard/SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = '@dashboard/SEND_MESSAGE_FAILED';

// GET LAST ACTIVITY
export const GET_LAST_ACTIVITY = '@dashboard/GET_LAST_ACTIVITY';
export const GET_LAST_ACTIVITY_SUCCESS = '@dashboard/GET_LAST_ACTIVITY_SUCCESS';
export const GET_LAST_ACTIVITY_FAILED = '@dashboard/GET_LAST_ACTIVITY_FAILED';

// UPDATE LAST ACTIVITY
export const UPDATE_LAST_ACTIVITY = '@dashboard/UPDATE_LAST_ACTIVITY';
export const UPDATE_LAST_ACTIVITY_SUCCESS =
  '@dashboard/UPDATE_LAST_ACTIVITY_SUCCESS';
export const UPDATE_LAST_ACTIVITY_FAILED =
  '@dashboard/UPDATE_LAST_ACTIVITY_FAILED';

// GET UNREAD MESSAGES
export const GET_UNREAD_MESSAGES = '@dashboard/GET_UNREAD_MESSAGES';
export const GET_UNREAD_MESSAGES_SUCCESS =
  '@dashboard/GET_UNREAD_MESSAGES_SUCCESS';
export const GET_UNREAD_MESSAGES_FAILED =
  '@dashboard/GET_UNREAD_MESSAGES_FAILED';

// READ CHAT MESSAGES
export const READ_CHAT_MESSAGE = '@dashboard/READ_CHAT_MESSAGE';
export const READ_CHAT_MESSAGE_SUCCESS = '@dashboard/READ_CHAT_MESSAGE_SUCCESS';
export const READ_CHAT_MESSAGE_FAILED = '@dashboard/READ_CHAT_MESSAGE_FAILED';

// GET POSSIBLES
export const GET_POSSIBLES = '@dashboard/GET_POSSIBLES';
export const GET_JOWA_POSSIBLES_SUCCESS =
  '@dashboard/GET_JOWA_POSSIBLES_SUCCESS';
export const GET_MARE_POSSIBLES_SUCCESS =
  '@dashboard/GET_MARE_POSSIBLES_SUCCESS';
export const GET_POSSIBLES_FAILED = '@dashboard/GET_POSSIBLES_FAILED';

// REPORT CATEGORY
export const REPORT_CATEGORY = '@dashboard/REPORT_CATEGORY';
export const REPORT_CATEGORY_SUCCESS = '@dashboard/REPORT_CATEGORY_SUCCESS';
export const REPORT_CATEGORY_FAILED = '@dashboard/REPORT_CATEGORY_FAILED';

// UPLOADING PHOTO MESSAGE
export const UPLOAD_PHOTO_MESSAGE = '@dashboard/UPLOAD_PHOTO_MESSAGE';
export const UPLOAD_PHOTO_MESSAGE_SUCCESS =
  '@dashboard/UPLOAD_PHOTO_MESSAGE_SUCCESS';
export const UPLOAD_PHOTO_MESSAGE_FAILED =
  '@dashboard/UPLOAD_PHOTO_MESSAGE_FAILED';

export const CANCEL_GET_MESSAGE_FETCH = '@dashboard/CANCEL_GET_MESSAGE_FETCH';

// DOWNLOADING PHOTO MESSAGE
export const DOWNLOAD_PHOTO_MESSAGE = '@dashboard/DOWNLOAD_PHOTO_MESSAGE';
export const DOWNLOAD_PHOTO_MESSAGE_SUCCESS =
  '@dashboard/DOWNLOAD_PHOTO_MESSAGE_SUCCESS';
export const DOWNLOAD_PHOTO_MESSAGE_FAILED =
  '@dashboard/DOWNLOAD_PHOTO_MESSAGE_FAILED';
